---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/ssd/cf:/config
      - /mnt/gm:/tv
      - /mnt/gm:/movies
    restart: unless-stopped