---
version: "2.1"
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbg
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK=002
    volumes:
      - /home/pi/dk/cf/nzbg:/config
      - /mnt/ssd/nzb:/av/nzb #optional
    ports:
      - 6789:6789
    restart: unless-stopped
