---
version: "2.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: over
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK=002
    volumes:
      - /home/pi/dk/cf/over:/config
    ports:
      - 5055:5055
    restart: unless-stopped

