version: '3.3'
services:
    rdtclient:
        container_name: rd
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - UMASK=002
        volumes:
            - /mnt/ssd/tor:/av/tor
            - /home/pi/dk/cf/rdcli:/data/db
            - /mnt/ssd/tor/bh:/av/tor/bh
        image: rogerfar/rdtclient
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '6500:6500'

