---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: son
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /home/pi/dk/cf/son:/config
      - /mnt/ssd:/av
    ports:
      - 8989:8989
    restart: unless-stopped
