---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jk
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
    volumes:
      - /home/pi/dk/cf/jk:/config
      - /mnt/ssd/tor/bh:/av/tor/bh
    ports:
      - 9117:9117
    restart: unless-stopped
